name:                santa-frontend-simple
version:             0.1.0.0
github:              "chfin/santa-frontend-simple"
license:             BSD3
author:              "Christoph Finkensiep"
maintainer:          "chfin@chfin.de"
copyright:           "2018-2020 Christoph Finkensiep"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/chfin/santa-frontent-simple#readme>

dependencies:
- base >= 4.7 && < 5
- type-of-html
- mwc-random
- vector
- text

library:
  source-dirs: src

executables:
  make-santa:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - santa-frontend-simple

tests:
  secretsanta-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - secretsanta
